### ISSUE TITLE
somethings error?

### ISSUE THREAD

**Issue by akzi** [ccsexyz/scanner#1]
root@fuwangqin-pc:/home/fuwangqin/go/src/scanner# ./scanner --target 101.227.201.29/22 --port 22
panic: reflect: call of reflect.Value.Int on zero Value [recovered]
	panic: reflect: call of reflect.Value.Int on zero Value

goroutine 1 [running]:
github.com/urfave/cli.HandleAction.func1(0xc42004dc68)
	/home/fuwangqin/go/src/github.com/urfave/cli/app.go:472 +0x2c8
panic(0x5998e0, 0xc42000c4a0)
	/usr/local/go/src/runtime/panic.go:491 +0x283
reflect.Value.Int(0x0, 0x0, 0x0, 0x5cf236)
	/usr/local/go/src/reflect/value.go:908 +0x141
golang.org/x/net/internal/netreflect.socketOf(0x6b8d20, 0xc42000e058, 0xc42000e058, 0x6b8d20, 0xc42000e058)
	/home/fuwangqin/go/src/golang.org/x/net/internal/netreflect/socket_posix.go:26 +0x196
golang.org/x/net/internal/netreflect.PacketSocketOf(0x6b8ae0, 0xc42000e058, 0xc42000e058, 0x6b8d20, 0xc42000e058)
	/home/fuwangqin/go/src/golang.org/x/net/internal/netreflect/socket.go:33 +0x7d
golang.org/x/net/ipv4.NewRawConn(0x6b8ae0, 0xc42000e058, 0xc42004d798, 0xc42000e060, 0x0)
	/home/fuwangqin/go/src/golang.org/x/net/ipv4/endpoint.go:181 +0xee
main.newScanner(0x16, 0xc420074720, 0x0, 0x1, 0x0, 0x0, 0x0)
	/home/fuwangqin/go/src/scanner/scanner.go:74 +0x2c0
main.main.func1(0xc4200a2000, 0x0, 0x0)
	/home/fuwangqin/go/src/scanner/main.go:45 +0x1a7
reflect.Value.call(0x593260, 0x5d94a0, 0x13, 0x5cef1b, 0x4, 0xc42004dc08, 0x1, 0x1, 0xc42004db88, 0x5c6f40, ...)
	/usr/local/go/src/reflect/value.go:434 +0x906
reflect.Value.Call(0x593260, 0x5d94a0, 0x13, 0xc42004dc08, 0x1, 0x1, 0x5cec90, 0x1, 0x5d00e3)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/urfave/cli.HandleAction(0x593260, 0x5d94a0, 0xc4200a2000, 0x0, 0x0)
	/home/fuwangqin/go/src/github.com/urfave/cli/app.go:481 +0x180
github.com/urfave/cli.(*App).Run(0xc420001500, 0xc420010140, 0x5, 0x5, 0x0, 0x0)
	/home/fuwangqin/go/src/github.com/urfave/cli/app.go:240 +0x507
main.main()
	/home/fuwangqin/go/src/scanner/main.go:52 +0x3c2
root@fuwangqin-pc:/home/fuwangqin/go/src/scanner#

**Comment by ccsexyz** [comment]
The program works only on linux.   
what kind of operating system do you use?

**Comment by akzi** [comment]
ubuntu 16.04

**Comment by ccsexyz** [comment]
I didn't reproduce this problem on my own Linux environment.For it was written a long time ago, I need some time to review it.

**Comment by akzi** [comment]
ok,3q

**Comment by ccsexyz** [comment]
It looks like ipv4.NewRawConn is called while the variable conn is nil.But I don't think that's possible.You could try to print the value of conn before calling ipv4.NewRawConn.
By the way, what's the version of your go?I found some files in the error message that I couldn't find on my machine.I'm using go1.9.
